
name: All Detection To Elastic

on:
  push:
  workflow_dispatch:

jobs:
   toml-validation:
    runs-on: ubuntu-latest
    env: 
      ELASTIC_KEY: ${{  secretes.ELASTIC_KEY  }}

    steps:
     
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
           python-version: '3.11.4'
      - run: pip install requests
      - run: python develop/toml_to_json.py
